apiVersion: v1
kind: Service
metadata:
   name: kafka
   labels:
     app: kafkaApp
spec:
  ports:
    - name: port1
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: port2
      port: 2181
      targetPort: 2181
  selector:
    app: kafkaApp
  type: LoadBalancer
